[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
ajo = "8WazH2EKrEzrwWwzh4KABve62CtQqKzR25WPa9WDbF3g"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
